logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081

spring:
  application:
    name: gateway