logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081

spring:
  application:
    name: gateway
  profiles:
    include:
      - nacos
  http:
    converters:
      preferred-json-mapper: gson

  gson:
    date-format: ''
    disable-html-escaping: ''
    disable-inner-class-serialization: ''
    enable-complex-map-key-serialization: ''
    exclude-fields-without-expose-annotation: ''
    field-naming-policy: ''
    generate-non-executable-json: ''
    lenient: ''
    long-serialization-policy: ''
    pretty-printing: ''
    serialize-nulls: 'true'
